### ISSUE TITLE
While running in target web, I get Error: Cannot find module 'fs'

### ISSUE THREAD

**Issue by vishalsatam** [microsoft/vscode-nls#48]
I keep getting this error when I try to import the vscode-jsonlanguage service in my webpack for target web using a umd-compat-loader.

```
Error: Cannot find module 'fs'
    at webpackMissingModule (main.js:8:1)
    at Object.<anonymous> (main.js:8:1)
    at ./node_modules/dependencyPackage/node_modules/vscode-json-languageservice/node_modules/vscode-nls/lib/main.js (main.js:499:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/dependencyPackagenode_modules/vscode-json-languageservice/lib/esm/parser/jsonParser.js (jsonParser.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/dependencyPackage/node_modules/vscode-json-languageservice/lib/esm/services/jsonCompletion.js (jsonCompletion.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
```

**I understand that this error occurs because I'm trying to import this for target web.** But I need to use it for my web application and I'm not able to get around this issue. Also, in my use case, I won't be using the filesystem at all for interacting with the data.

Is it possible to add support for web target builds? If not, please suggest a workaround that I can try.

I've already tried fs empty in webpack.config.js
```
  node: {
    fs: 'empty'
  },
  externals: {
    "fs": "fs"
  }
```

and also I've tried adding browsr.fs: false to my package.json file.
```
  "browser": {
    "fs": false
  },
```

None of these workarounds solved the issue.

**Comment by vishalsatam** [comment]
I'm closing this issue. The following configuration in webpack worked for me.

```
  node: {
    fs: 'empty',
  },
```
